name: wikidart
description: A Dart library for fetching data through Wikimedia API endpoints.
version: 0.0.1
homepage: https://github.com/flikkr/wikidart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: any
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
